"""Generate the SEO head block, robots.txt and sitemap.xml for every page.

Run:  python tools/build_seo.py          # rewrite everything
      python tools/build_seo.py --check  # fail if anything is stale (for CI)

WHY A GENERATOR AND NOT HAND-EDITED TAGS
----------------------------------------
There are nine pages and roughly fifteen head tags each. Hand-maintained, they
rot the moment anyone adds a page: a missing canonical or a description copied
from a neighbouring page is invisible in the browser and quietly expensive in
search. Here the page table below is the single source of truth, this script
writes a clearly-marked managed block, and tests/test_seo.py proves the result.

WHAT THIS BUYS AND WHAT IT DOES NOT
-----------------------------------
On-page SEO makes a page *eligible* to rank and controls how it is presented
once it does — the title in the result, the snippet, the social card, the rich
results. It does not create authority. "Quantum Ascent" as a bare phrase is
already held by several established businesses with exact-match domains, so
this file deliberately targets the descriptive, winnable queries instead
(interactive quantum computing course, quantum computing myths, browser qubit
simulator, QAOA Max-Cut tutorial) while keeping the brand in every title so
Google learns to associate it with quantum computing rather than consulting.
See docs/seo.md.
"""

import html
import re
import sys
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
WEB = REPO / "website"
SITE = "https://quantum-ascent-77617.web.app"
OG_IMAGE = f"{SITE}/assets/og-image.png"
OG_ALT = ("Quantum Ascent — learn quantum computing by climbing. "
          "Six basecamps, runs in your browser, no install.")
TWITTER = None          # no brand account yet; omit rather than invent one

BEGIN = "<!-- SEO:BEGIN — generated by tools/build_seo.py; edit that file, not this block -->"
END = "<!-- SEO:END -->"

# Pages served from one file under many ?id= values.
PARAM_PAGES = {"module.html", "lab.html"}
MODULE_IDS = [f"{i:02d}" for i in range(1, 7)]

# ---------------------------------------------------------------- page table
# title: <= 65 chars, brand included, most distinctive words first.
# desc:  70-165 chars, written to be *read* in a result, not stuffed.
PAGES = {
    "index.html": dict(
        title="Quantum Ascent — Learn Quantum Computing by Climbing",
        desc=("A free, interactive quantum computing course. Build real circuits in your "
              "browser — no install, no account — from your first qubit to QAOA."),
        priority="1.0", changefreq="weekly", crumb=None,
    ),
    "ascent.html": dict(
        title="The Ascent · Six Basecamps — Quantum Ascent",
        desc=("The full route map: six basecamps from qubits and superposition to a QAOA "
              "Max-Cut summit. Track your XP, badges and progress as you climb."),
        priority="0.9", changefreq="weekly", crumb="The Ascent",
    ),
    "lab.html": dict(
        title="Browser Lab · Build Quantum Circuits — Quantum Ascent",
        desc=("Build and run real quantum circuits in your browser. An exact statevector "
              "simulator with instant feedback, Qiskit code shown as you go. No install."),
        priority="0.9", changefreq="monthly", crumb="Browser Lab",
    ),
    "module.html": dict(
        title="Basecamps · Quantum Computing Lessons — Quantum Ascent",
        desc=("Work a basecamp: play with an interactive widget, do the physics in the "
              "browser or in Qiskit, then prove it with a quiz. Six lessons, beginner-first."),
        priority="0.9", changefreq="monthly", crumb="Basecamps",
    ),
    "myths.html": dict(
        title="Quantum Computing Myths, Autopsied — Quantum Ascent",
        desc=("Six famous quantum computing myths, each dissected with a live simulation you "
              "run yourself. Try to send a faster-than-light signal. Watch physics refuse."),
        priority="0.9", changefreq="monthly", crumb="Myth Autopsy",
    ),
    "widgets.html": dict(
        title="Interactive Quantum Widgets — Quantum Ascent",
        desc=("Eight self-contained quantum computing visualisations: Bloch sphere sampler, "
              "gate playground, entanglement explorer, Max-Cut painter. Free to embed."),
        priority="0.8", changefreq="monthly", crumb="Widget Gallery",
    ),
    "analogy-studio.html": dict(
        title="Analogy Studio · Explain Quantum Your Way — Quantum Ascent",
        desc=("Generate a myth-free AI prompt that explains any quantum concept through a "
              "topic you already know — then audit the answer against the ground rules."),
        priority="0.7", changefreq="monthly", crumb="Analogy Studio",
    ),
    "assessment.html": dict(
        title="Quantum Concept Diagnostic · Before & After — Quantum Ascent",
        desc=("Ten questions on the ideas beginners usually get wrong. Take it before and "
              "after the course and measure exactly what changed. Scored in your browser."),
        priority="0.7", changefreq="monthly", crumb="Diagnostic",
    ),
    "kit-check.html": dict(
        title="Kit Check · What You Need First — Quantum Ascent",
        desc=("A ten-minute prerequisite check before Basecamp 1: radians, sin², Python "
              "dictionaries and functions. No complex numbers needed. Repairs the gaps."),
        priority="0.7", changefreq="monthly", crumb="Kit Check",
    ),
}


# ------------------------------------------------------------- JSON-LD blocks
def ld(obj_json):
    return f'<script type="application/ld+json">\n{obj_json}\n</script>'


def json_dumps(o, indent=2):
    import json
    return json.dumps(o, indent=indent, ensure_ascii=False)


def breadcrumb_ld(name, url):
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": f"{SITE}/"},
            {"@type": "ListItem", "position": 2, "name": name, "item": url},
        ],
    }


def website_ld():
    return {
        "@context": "https://schema.org",
        "@type": "WebSite",
        "name": "Quantum Ascent",
        "alternateName": "Quantum Ascent — quantum computing course",
        "url": f"{SITE}/",
        "description": PAGES["index.html"]["desc"],
        "inLanguage": "en",
    }


def course_ld():
    """Course schema, filled honestly.

    `hasCourseInstance` is required for the rich result. Ours is genuinely
    self-paced and online with no scheduled cohort, so it says exactly that
    rather than inventing a start date.
    """
    return {
        "@context": "https://schema.org",
        "@type": "Course",
        "name": "Quantum Ascent — Learn Quantum Computing by Climbing",
        "description": (
            "A free, hands-on introduction to quantum computing in six basecamps: qubits and "
            "superposition, gates and circuits, entanglement, Hamiltonians and energy, the "
            "variational principle, and a QAOA Max-Cut capstone. Every basecamp can be "
            "completed entirely in the browser against an exact statevector simulator, or in "
            "Jupyter/Colab with real Qiskit."),
        "url": f"{SITE}/",
        "inLanguage": "en",
        "isAccessibleForFree": True,
        "teaches": [
            "Qubits and superposition", "The Born rule", "Quantum gates and circuits",
            "Entanglement and no-signalling", "Hamiltonians and expectation values",
            "The variational principle", "QAOA and Max-Cut",
        ],
        "educationalLevel": "Beginner",
        "coursePrerequisites": (
            "High-school algebra and trigonometry (radians). Basic Python helps but is not "
            "required. No prior quantum physics, and no complex numbers."),
        "provider": {
            "@type": "Organization",
            "name": "Quantum Ascent",
            "url": f"{SITE}/",
        },
        "offers": {
            "@type": "Offer",
            "category": "Free",
            "price": "0",
            "priceCurrency": "USD",
            "availability": "https://schema.org/InStock",
        },
        "hasCourseInstance": {
            "@type": "CourseInstance",
            "courseMode": "online",
            "courseWorkload": "PT8H",
            "inLanguage": "en",
            "instructor": {"@type": "Organization", "name": "Quantum Ascent"},
        },
    }


def itemlist_ld():
    """The six basecamps as an ordered list — helps Google understand the route
    and can surface the individual lessons."""
    import json as _j
    modules = _j.loads((WEB / "assets" / "data" / "modules.json").read_text(encoding="utf-8"))
    items = []
    for i, m in enumerate(modules["modules"], start=1):
        items.append({
            "@type": "ListItem",
            "position": i,
            "name": f"Basecamp {m['id']}: {m['title']}",
            "description": m["subtitle"],
            "url": f"{SITE}/module.html?id={m['id']}",
        })
    return {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "The six basecamps of Quantum Ascent",
        "itemListOrder": "https://schema.org/ItemListOrderAscending",
        "numberOfItems": len(items),
        "itemListElement": items,
    }


TAG = re.compile(r"<[^>]+>")


def _plain(s):
    """HTML fragment -> single-line plain text, for schema string fields."""
    s = TAG.sub(" ", s)
    s = html.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def faq_ld():
    """Build FAQPage from the myths page itself, so the two cannot drift.

    The Myth Autopsy is already a list of question/answer pairs, which makes it
    the strongest rich-result opportunity on the site — and the queries it
    targets ("can quantum computers send messages faster than light") are ones
    a small site can genuinely win.
    """
    src = (WEB / "myths.html").read_text(encoding="utf-8")
    claims = re.findall(r'<div class="myth-claim">.*?<q>(.*?)</q>', src, re.S)
    answers = re.findall(r'<b class="say">(.*?)</b>', src, re.S)
    if len(claims) != len(answers):
        raise SystemExit(
            f"myths.html: {len(claims)} claims but {len(answers)} verdicts — "
            "FAQ schema would be mismatched. Fix the page, then rerun.")
    qs = []
    for c, a in zip(claims, answers):
        qs.append({
            "@type": "Question",
            "name": _plain(c),
            "acceptedAnswer": {"@type": "Answer", "text": _plain(a)},
        })
    return {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": qs,
    }


def jsonld_for(name):
    out = []
    cfg = PAGES[name]
    url = f"{SITE}/" if name == "index.html" else f"{SITE}/{name}"
    if name == "index.html":
        out += [website_ld(), course_ld()]
    if name == "ascent.html":
        out.append(itemlist_ld())
    if name == "myths.html":
        out.append(faq_ld())
    if cfg["crumb"]:
        out.append(breadcrumb_ld(cfg["crumb"], url))
    return out


# ------------------------------------------------------------- the head block
CANONICAL_SCRIPT = """<script>
/* This file serves six logical URLs (?id=01 … ?id=06) from one document.
   Without rewriting the canonical, all six basecamps collapse into a single
   indexed URL and five of them become invisible — which is most of the site's
   actual content. Runs before render so a crawler sees the corrected value. */
(function () {
  var id = new URLSearchParams(location.search).get("id");
  if (!id || !/^0[1-6]$/.test(id)) return;
  var url = location.origin + location.pathname + "?id=" + id;
  var c = document.querySelector('link[rel="canonical"]');
  if (c) c.setAttribute("href", url);
  var o = document.querySelector('meta[property="og:url"]');
  if (o) o.setAttribute("content", url);
})();
</script>"""


def head_block(name):
    cfg = PAGES[name]
    url = f"{SITE}/" if name == "index.html" else f"{SITE}/{name}"
    t = html.escape(cfg["title"], quote=True)
    d = html.escape(cfg["desc"], quote=True)

    lines = [
        BEGIN,
        f'<title>{t}</title>',
        f'<meta name="description" content="{d}">',
        f'<link rel="canonical" href="{url}">',
        '<meta name="robots" content="index, follow, max-image-preview:large, '
        'max-snippet:-1, max-video-preview:-1">',
        '',
        '<!-- Open Graph (LinkedIn, WhatsApp, Slack, Discord, Facebook) -->',
        '<meta property="og:site_name" content="Quantum Ascent">',
        f'<meta property="og:type" content="{"website" if name == "index.html" else "article"}">',
        f'<meta property="og:title" content="{t}">',
        f'<meta property="og:description" content="{d}">',
        f'<meta property="og:url" content="{url}">',
        f'<meta property="og:image" content="{OG_IMAGE}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{html.escape(OG_ALT, quote=True)}">',
        '<meta property="og:locale" content="en_US">',
        '',
        '<!-- Twitter / X card -->',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{t}">',
        f'<meta name="twitter:description" content="{d}">',
        f'<meta name="twitter:image" content="{OG_IMAGE}">',
        '',
        '<!-- Icons & theme -->',
        '<link rel="icon" href="/favicon.ico" sizes="32x32">',
        '<link rel="icon" href="/favicon.svg" type="image/svg+xml">',
        '<link rel="apple-touch-icon" href="/apple-touch-icon.png">',
        '<meta name="theme-color" content="#1f7a4d">',
        '<meta name="author" content="Quantum Ascent">',
        '',
        '<!-- Speed up the third-party origins we do use -->',
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
        '<link rel="dns-prefetch" href="https://cdn.jsdelivr.net">',
    ]

    for obj in jsonld_for(name):
        lines += ['', ld(json_dumps(obj))]

    if name in PARAM_PAGES:
        lines += ['', CANONICAL_SCRIPT]

    lines.append(END)
    return "\n".join(lines)


# ------------------------------------------------------------------ rewriting
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
OLD_TITLE = re.compile(r"[ \t]*<title>.*?</title>\n?", re.S | re.I)
OLD_DESC = re.compile(r'[ \t]*<meta\s+name=["\']description["\'][^>]*>\n?', re.I)


def rewrite_page(path):
    src = path.read_text(encoding="utf-8")
    block = head_block(path.name)

    if BLOCK_RE.search(src):
        return BLOCK_RE.sub(lambda _: block, src)

    # First run: strip the hand-written title/description (the table owns them
    # now) and insert the block just before </head>.
    src = OLD_TITLE.sub("", src, count=1)
    src = OLD_DESC.sub("", src, count=1)
    m = re.search(r"</head>", src, re.I)
    if not m:
        raise SystemExit(f"{path.name}: no </head> to insert into")
    return src[:m.start()] + block + "\n" + src[m.start():]


def build_robots():
    return f"""# Quantum Ascent — https://github.com/sahgyan9/quantum-ascent
# Everything here is free educational content; crawl all of it.

User-agent: *
Allow: /

# Query-string variants of the two templated pages are real, distinct lessons
# and are listed explicitly in the sitemap. Nothing is disallowed.

Sitemap: {SITE}/sitemap.xml
"""


def build_sitemap():
    today = date.today().isoformat()
    urls = []

    def add(loc, pri, freq):
        urls.append(f"""  <url>
    <loc>{html.escape(loc, quote=True)}</loc>
    <lastmod>{today}</lastmod>
    <changefreq>{freq}</changefreq>
    <priority>{pri}</priority>
  </url>""")

    add(f"{SITE}/", PAGES["index.html"]["priority"], PAGES["index.html"]["changefreq"])
    for name, cfg in PAGES.items():
        if name == "index.html":
            continue
        if name in PARAM_PAGES:
            # The bare file is a template; the six ?id= URLs are the content.
            for mid in MODULE_IDS:
                add(f"{SITE}/{name}?id={mid}", cfg["priority"], cfg["changefreq"])
        else:
            add(f"{SITE}/{name}", cfg["priority"], cfg["changefreq"])

    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            + "\n".join(urls) + "\n</urlset>\n")


def main():
    check = "--check" in sys.argv
    stale = []

    targets = {WEB / n: rewrite_page(WEB / n) for n in PAGES}
    targets[WEB / "robots.txt"] = build_robots()
    targets[WEB / "sitemap.xml"] = build_sitemap()

    for path, content in targets.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        if check:
            stale.append(path.name)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"{'updated' if current else 'created'} "
                  f"{path.relative_to(REPO).as_posix()}")

    if check and stale:
        sys.exit("SEO output is stale, run `python tools/build_seo.py`: "
                 + ", ".join(sorted(stale)))
    if check:
        print("SEO output is up to date.")


if __name__ == "__main__":
    main()
